#!/bin/bash

if [ ! -d ".git" ]; then
    echo "Not a git repository (or any of the parent directories): .git. Do NOT download the repository as a zip file from GitHub.com! Please download Mars by cloning the Git repository: 'git clone https://github.com/danielkrupinski/mars.git'"
    exit
else
    read -p "This will delete local code changes. Are you sure? (y/n)" -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        git reset --hard
        ./update
    fi
fi
